# Basic
title: LILIAN
subtitle: 心灵之窗
description: 书写生活，充实自我
# 头像里面的标题
avatarTitle: 李文宝
# 头像里面的描述
avatarDesc: 数据挖掘 / 机器学习
url: "http://lilian.info"

# Comment
comment:
    # disqus: lilian
    duoshuo: lilian 

# Social
social:
    weibo: 2344041987
    github: dearLilian
    #gsite: liliandreamworld
    csdn: lilianforever
    # twitter: 
    mail: liwenbao930116@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: e572ae9801b3a18891f123796b889f77

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-88738012-1   
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/dearLilian/dearLilian.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》

markdown: kramdown

permalink: /blog/:year/:month/:title.html 
kramdown:

  auto_ids: true,

  footnote_nr: 1

  entity_output: as_char

  toc_levels: 1..6

  enable_coderay: false


# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: 

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 分类, description: tags, url: '/tags'}
    - {title: 留言板, description: messages, url: '/messages'}
    - {title: 资源链接, description: links, url: '/links'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"